completed task map_reduce
iavianm/ru-study-ruby pull request #2
Opened 2022-07-14 14:21 UTC by iavianm

task map/reduce

2022-08-11 15:49 UTC, NickelGit requested changes

2022-08-11 16:19 UTC, iavianm commented on test/exercise/fp/solution.rb
> +        end
Извини, ты посмотрел почему то предыдущую версию, я уже все переписал пару дней назад, вообще все по другому ((((

2022-08-11 17:43 UTC, NickelGit commented on test/exercise/fp/solution.rb
> +        end
Да, но половина замечаний еще актуальна. Пройдись пжлст по ним.

2023-07-24 06:50 UTC, YJorge commented on test/exercise/fp/solution.rb
> +      def rating_condition?(film)
не очень подходящее название. из названия не ясно, что метод проверяет

2023-07-24 06:52 UTC, YJorge commented on test/exercise/fp/solution.rb
> +            memo += 1 if char == 'и'
как было написано в одном из комментариев до этого, лучше использовать другой подход для подсчета  букв,  например `.count`

2023-07-25 05:30 UTC, YJorge commented on test/exercise/fp/solution.rb
> +          film['rating_kinopoisk'].to_f if many_countries?(film)
`multiple_countries` будет лучше

2023-07-25 05:33 UTC, YJorge commented on test/exercise/fp/solution.rb
> +      def film_rating(film, threshold)
если метод возвращает true/false в наименовании должен быть `?`. Но `film_rating?` не будет отражать суть метода

2023-07-26 06:13 UTC, YJorge commented on test/exercise/fp/solution.rb
> +        result.compact.join.chars.count('и')
Лишние преобразования

```
result = ['aa', 'bb', 'cc', nil]
result.compact - ['aa', 'bb', 'cc']
result.compact.join - 'aabbcc'
result.compact.join.chars -  ['a', 'a', 'b', 'b', 'c', 'c']
```
1. join вполняется и для массива с nil
2. count считает и данные в строке

Вообще, если используется итерация через массив(будь то each или map), лучше внутри провести такие преобразования, чтобы после не приходилось изменять полученный массив

2023-07-26 08:44 UTC, YJorge commented on test/exercise/fp/solution.rb
> +        end.join.count('и')
это тоже не очень хороший вариант.  В массиве может быть не одно - два значения, а тысячи и соединять это все в одну строку - так себе вариант. Если необходимо считать количество букв в названии, то лучше и искать в названии, а не в единой строке из названий

2023-07-27 05:54 UTC, YJorge approved these changes

2023-07-27 07:55 UTC, merged